<?php
require_once __DIR__.'/report_data.php';
$trendFrom=input_text($_GET,'date_from')?:date('Y-01-01');$trendTo=input_text($_GET,'date_to')?:date('Y-m-d');
[$trendStart,$trendEnd]=report_range($trendFrom,$trendTo);
$trendService=(int)($_GET['trend_service']??0);$trendRevenue=$user['role']==='bookkeeper'||($user['role']==='admin'&&($_GET['trend_metric']??'')==='revenue');
$trendWhere='';$trendArgs=[$trendStart,$trendEnd];
if($user['role']==='parishioner'){$trendWhere.=' AND a.user_id=?';$trendArgs[]=$user['id'];}
elseif($user['role']!=='admin'){$trendWhere.=' AND a.parish_id=?';$trendArgs[]=$user['parish_id'];}
if($trendService){$trendWhere.=' AND a.service_id=?';$trendArgs[]=$trendService;}
$trendSql=$trendRevenue?"SELECT DATE_FORMAT(COALESCE(p.verified_at,p.paid_at),'%Y-%m') month,SUM(p.amount) value FROM payments p JOIN applications a ON a.id=p.application_id WHERE p.status IN ('completed','refunded') AND COALESCE(p.verified_at,p.paid_at) BETWEEN ? AND ? $trendWhere GROUP BY month":"SELECT DATE_FORMAT(a.created_at,'%Y-%m') month,COUNT(*) value FROM applications a WHERE a.created_at BETWEEN ? AND ? $trendWhere GROUP BY month";
$trendValues=[];$last=new DateTimeImmutable(substr($trendTo,0,7).'-01');$first=max(new DateTimeImmutable(substr($trendFrom,0,7).'-01'),$last->modify('-11 months'));
for($date=$first;$date<=$last;$date=$date->modify('+1 month'))$trendValues[$date->format('Y-m')]=0;
foreach($conn->execute_query($trendSql,$trendArgs) as $row)if(array_key_exists($row['month'],$trendValues))$trendValues[$row['month']]=(float)$row['value'];
$trendServices=$user['role']==='admin'?$conn->query('SELECT id,name FROM services ORDER BY name')->fetch_all(MYSQLI_ASSOC):($user['role']==='parishioner'?$conn->execute_query('SELECT DISTINCT s.id,s.name FROM services s JOIN applications a ON a.service_id=s.id WHERE a.user_id=? ORDER BY s.name',[$user['id']])->fetch_all(MYSQLI_ASSOC):$conn->execute_query('SELECT id,name FROM services WHERE parish_id=? ORDER BY name',[$user['parish_id']])->fetch_all(MYSQLI_ASSOC));
$maximum=max(1,...array_values($trendValues));$points=[];$i=0;foreach($trendValues as $value){$points[]=(40+$i*620/max(1,count($trendValues)-1)).','.(190-160*$value/$maximum);$i++;}
?>
<section class="card"><div class="card-body"><h2><?= $trendRevenue?'Verified revenue':'Service applications' ?> over time</h2><form method="get" class="filter-bar"><input type="hidden" name="date_from" value="<?= h($trendFrom) ?>"><input type="hidden" name="date_to" value="<?= h($trendTo) ?>"><label>Service<select name="trend_service"><option value="0">All services</option><?php foreach($trendServices as $service): ?><option value="<?= (int)$service['id'] ?>" <?= $trendService===(int)$service['id']?'selected':'' ?>><?= h($service['name']) ?></option><?php endforeach; ?></select></label><?php if($user['role']==='admin'): ?><label>Measure<select name="trend_metric"><option value="applications">Applications</option><option value="revenue" <?= $trendRevenue?'selected':'' ?>>Verified revenue</option></select></label><?php endif; ?><button>Update trend</button></form>
<p><?= h($trendFrom) ?> to <?= h($trendTo) ?>; showing up to the last 12 months. <?= $trendRevenue?'Gross verified payments; refunds are shown separately in financial reports.':'Counts by application submission date.' ?></p>
<svg viewBox="0 0 700 235" role="img" aria-label="Monthly <?= $trendRevenue?'verified revenue':'applications' ?> line chart; exact values in the table below" style="width:100%;max-height:280px"><path d="M40 20V190H670" fill="none" stroke="#94a3b8"/><text x="0" y="20" font-size="12"><?= h(number_format($maximum)) ?></text><text x="20" y="195" font-size="12">0</text><polyline points="<?= h(implode(' ',$points)) ?>" fill="none" stroke="#43658b" stroke-width="3"/><?php $i=0;foreach($trendValues as $month=>$value):[$x,$y]=explode(',',$points[$i++]); ?><circle cx="<?= $x ?>" cy="<?= $y ?>" r="5" fill="#43658b"><title><?= h($month.': '.number_format($value,$trendRevenue?2:0)) ?></title></circle><text x="<?= $x ?>" y="215" text-anchor="middle" font-size="10"><?= h(substr($month,2)) ?></text><?php endforeach; ?></svg>
<details><summary>View exact monthly values</summary><table><thead><tr><th>Month</th><th><?= $trendRevenue?'Revenue (PHP)':'Applications' ?></th></tr></thead><tbody><?php foreach($trendValues as $month=>$value): ?><tr><td><?= h($month) ?></td><td><?= number_format($value,$trendRevenue?2:0) ?></td></tr><?php endforeach; ?></tbody></table></details></div></section>
