"""Targeted browser/API regressions against the latest isolated synthetic fixture."""
import os, sys, json, subprocess, time, re, urllib.parse
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / '.browser-tools'))
from playwright.sync_api import sync_playwright
fixture = json.loads((ROOT / 'storage/private/revision-fixture.json').read_text())
assert fixture['database'].startswith('vicar_revision_')
PHP = 'C:/xampp/php/php.exe'
MYSQL = 'C:/xampp/mysql/bin/mysql.exe'
base = 'http://127.0.0.1:8773'
env = os.environ.copy()
env.update(DB_NAME=fixture['database'], APP_ENV='local', APP_URL=base)
out = ROOT / 'revision-evidence/enhancements'
out.mkdir(parents=True, exist_ok=True)
results, errors = [], []
def check(name, valid):
    results.append({'test':name, 'passed':bool(valid)})
    print(('PASS ' if valid else 'FAIL ') + name, flush=True)
def sql(query):
    return subprocess.check_output([MYSQL, '--host=127.0.0.1', '--user=root', '--batch', '--skip-column-names', fixture['database'], '-e', query], text=True).strip()
def session_value(context, key, value):
    sid = next(c['value'] for c in context.cookies() if c['name'] == 'PHPSESSID')
    test_env = env.copy(); test_env['TEST_SESSION_ID'] = sid
    code = "session_save_path('storage/private/sessions'); session_id(getenv('TEST_SESSION_ID')); session_start(); $_SESSION['"+key+"']="+str(value)+"; session_write_close();"
    subprocess.run([PHP, '-r', code], env=test_env, cwd=ROOT, check=True, capture_output=True)
# All mutations are limited to the asserted synthetic database.
sql("UPDATE users SET two_factor_enabled=0,language='en',phone='09123456789' WHERE id IN (1,2,3,4)")
sql("DELETE FROM security_rate_limits")
sql("UPDATE services SET requirements_note='Bring the original certificate.\n<script>window.notesExecuted=true</script>' WHERE id=1")
sql("INSERT INTO services(parish_id,name,description,fee,max_daily_limit,requirements_note,status) VALUES(1,'No notes test','Test',0,0,'','active')")
empty_id = sql('SELECT MAX(id) FROM services')
log = (ROOT / 'storage/private/enhancement-browser.log').open('w')
server = subprocess.Popen([PHP, '-d', 'disable_functions=mail,curl_exec,fsockopen,stream_socket_client', '-S', '127.0.0.1:8773', '-t', str(ROOT)], cwd=ROOT, env=env, stdout=log, stderr=log)
try:
    time.sleep(1)
    with sync_playwright() as pw:
        browser = pw.chromium.launch(executable_path='C:/Program Files/Google/Chrome/Application/chrome.exe', headless=True)
        context = browser.new_context(viewport={'width':1440, 'height':1000})
        context.route('**/*', lambda route: route.continue_() if route.request.url.startswith(base) or route.request.url.startswith('data:') else route.abort())
        page = context.new_page()
        page.on('pageerror', lambda error: errors.append(str(error)))
        def login(uid):
            page.goto(base + '/public/login.php')
            page.locator('[name=email]').fill(f'audit{uid}@example.invalid')
            page.locator('[name=password]').fill(fixture['password'])
            page.locator('button[type=submit]').click()
            page.wait_for_url('**/dashboard.php')
        def verify():
            page.locator('[name=password]').fill(fixture['password'])
            page.get_by_role('button', name='Verify', exact=True).click()
            page.wait_for_load_state()
        def api(path, body):
            return page.evaluate("""async ([path,body]) => {
                const response = await fetch(path, {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
                return {status:response.status, data:await response.json()};
            }""", [path,body])
        login(4)
        page.goto(base + '/parishioner/apply_service.php')
        page.locator('#selParish').select_option('1')
        page.locator('#btnStep1').click()
        page.locator('.svc-card[data-id="1"]').click()
        page.locator('#btnStep2').click()
        check('Selected service notes appear before date/time', page.locator('#requirementNotesStep').is_visible() and not page.locator('#selSchedule').is_visible())
        check('Requirement notes render as text, not executable HTML', '<script>' in page.locator('#requirementNotesText').inner_text() and not page.evaluate('Boolean(window.notesExecuted)'))
        page.screenshot(path=str(out / 'requirements-desktop.png'))
        page.get_by_role('button', name='Continue to schedule').click()
        check('Continue from notes opens scheduling', page.locator('#selSchedule').is_visible())
        page.evaluate('goStep(2)')
        page.locator('.svc-card[data-id="'+empty_id+'"]').click()
        page.locator('#btnStep2').click()
        check('Service without notes skips note screen', page.locator('#selSchedule').is_visible() and not page.locator('#requirementNotesStep').is_visible())
        page.evaluate('goStep(2)')
        page.locator('.svc-card[data-id="1"]').click()
        page.locator('#btnStep2').click()
        page.set_viewport_size({'width':390,'height':844})
        page.wait_for_timeout(500)
        check('Mobile sidebar stays off canvas', page.locator('.sidebar').bounding_box()['x'] + page.locator('.sidebar').bounding_box()['width'] <= 1)
        check('Mobile notes have no horizontal overflow', page.evaluate('document.documentElement.scrollWidth <= innerWidth'))
        page.screenshot(path=str(out / 'requirements-mobile.png'), full_page=True)
        page.goto(base + '/parishioner/security.php')
        check('Security checkbox retains compact dimensions', page.locator('[type=checkbox]').bounding_box()['width'] <= 20)
        page.screenshot(path=str(out / 'security-mobile.png'), full_page=True)
        page.set_viewport_size({'width':1440,'height':1000})
        login(2)
        check('Secretary normal dashboard does not prompt', '/staff/dashboard.php' in page.url)
        page.goto(base + '/staff/applications.php')
        check('Secretary Applications still requires password', 'verify_password.php' in page.url)
        verify()
        session_value(context, 'last_activity', int(time.time()) - 360)
        session_value(context, 'sensitive_until', 0)
        page.goto(base + '/staff/records.php')
        check('Secretary verification survives six minutes of inactivity', 'records.php' in page.url)
        page.goto(base + '/staff/applications.php')
        page.evaluate('viewApp(1)')
        page.locator('#viewContent h2').wait_for()
        check('Application detail content is stacked, not a loading flex row', page.locator('#viewContent').evaluate('(e)=>getComputedStyle(e).display') == 'block')
        page.screenshot(path=str(out / 'application-modal.png'))
        page.goto(base + '/staff/messages.php')
        r = api('messages.php?ajax=send', {'receiver_id':4,'body':'Enhancement message','send_sms':True,'send_email':True})
        check('Secretary message dispatches both chosen channels', r['data'].get('delivery',{}).get('sms_simulated') == 1 and r['data'].get('delivery',{}).get('email_simulated') == 1)
        check('Delivery feedback is visible', page.locator('#deliveryFeedback').is_visible())
        r = api('messages.php?ajax=send', {'receiver_id':5,'body':'Forbidden','send_sms':True})
        check('Cross-parish message remains forbidden', r['status'] in (403,422))
        page.get_by_role('button', name='Compose', exact=False).click()
        check('Compose exposes SMS and email options', page.locator('#composeSms').is_visible() and page.locator('#composeEmail').is_visible())
        page.screenshot(path=str(out / 'compose.png'))
        login(3)
        page.goto(base + '/staff/finance.php')
        check('Bookkeeper overview does not require extra verification', 'finance.php' in page.url)
        page.goto(base + '/staff/accounting.php')
        check('Bookkeeper Accounting still requires password', 'verify_password.php' in page.url)
        verify()
        session_value(context, 'last_activity', int(time.time()) - 360)
        session_value(context, 'sensitive_until', 0)
        page.goto(base + '/staff/accounting.php')
        check('Bookkeeper verification survives six minutes', 'accounting.php' in page.url)
        check('Accounting has clear active tab', page.locator('.accounting-tabs [aria-current=page]').count() == 1)
        page.screenshot(path=str(out / 'accounting.png'))
        session_value(context, 'last_activity', int(time.time()) - 1801)
        page.goto(base + '/staff/accounting.php')
        check('Idle expiry still requires a full login', 'public/login.php' in page.url)
        login(1)
        page.goto(base + '/admin/users.php?action=edit&id=2')
        check('Admin edit form loads selected account', page.locator('[name=email]').input_value() == 'audit2@example.invalid')
        check('Admin does not receive staff verification challenge', 'verify_password.php' not in page.url)
        doc = sql("SELECT id,uploaded_files FROM applications WHERE uploaded_files IS NOT NULL AND uploaded_files NOT IN ('{}','[]','') LIMIT 1").split('\t',1)
        key = next(iter(json.loads(doc[1])))
        url = base + '/public/document.php?app=' + doc[0] + '&key=' + urllib.parse.quote(key)
        response = context.request.get(url)
        check('Authorized document opens inline with actual MIME', response.status == 200 and response.headers.get('content-disposition','').startswith('inline;') and response.headers.get('content-type') in ['image/png','image/jpeg','application/pdf'])
        response = context.request.get(url + '&download=1')
        check('Explicit document download remains available', response.headers.get('content-disposition','').startswith('attachment;'))
        for uid in [1,2,3,4]:
            sql(f'UPDATE users SET two_factor_enabled=1 WHERE id={uid}')
            page.goto(base + '/public/login.php')
            page.locator('[name=email]').fill(f'audit{uid}@example.invalid')
            page.locator('[name=password]').fill(fixture['password'])
            page.locator('button[type=submit]').click()
            page.wait_for_url('**/verify_otp.php')
            codes = re.findall(r'Your login code is (\d{6})', (ROOT / 'storage/private/email.log').read_text())
            page.locator('[name=otp]').fill(codes[-1])
            page.locator('[name=verify_otp]').click()
            page.wait_for_url('**/dashboard.php')
            check(f'Login OTP preserved for role user {uid}', 'dashboard.php' in page.url)
            sql(f'UPDATE users SET two_factor_enabled=0 WHERE id={uid}')
        check('No browser JavaScript errors', not errors)
        browser.close()
except Exception as error:
    results.append({'test':'Browser execution','passed':False,'error':str(error)})
    print(str(error), flush=True)
finally:
    server.terminate(); server.wait(timeout=10); log.close()
    (out / 'results.json').write_text(json.dumps({'tests':results,'javascript_errors':errors},indent=2))
if any(not row['passed'] for row in results): raise SystemExit(1)
