<?php
require_once __DIR__.'/../includes/access.php';
$pid=(int)($_GET['parish_id']??$user['parish_id']??0);$month=$_GET['month']??date('Y-m');
if(!preg_match('/^[0-9]{4}-(0[1-9]|1[0-2])$/',$month))$month=date('Y-m');
$first=new DateTimeImmutable($month.'-01');$days=(int)$first->format('t');$offset=(int)$first->format('N')-1;
$parishes=$conn->query("SELECT id,name FROM parishes WHERE status='active'")->fetch_all(MYSQLI_ASSOC);if(!$pid&&$parishes)$pid=(int)$parishes[0]['id'];
$events=$conn->execute_query("SELECT * FROM events WHERE parish_id=? AND status='active' AND event_date>=? AND event_date<? ORDER BY event_date",[$pid,$first->format('Y-m-d'),$first->modify('+1 month')->format('Y-m-d')])->fetch_all(MYSQLI_ASSOC);$byDay=[];foreach($events as $event)$byDay[(int)date('j',strtotime($event['event_date']))][]=$event;
foreach($conn->execute_query("SELECT a.id,a.schedule event_date,s.name title FROM applications a JOIN services s ON s.id=a.service_id WHERE a.user_id=? AND a.parish_id=? AND a.status IN ('pending','approved') AND a.schedule>=? AND a.schedule<? ORDER BY a.schedule",[$user['id'],$pid,$first->format('Y-m-d'),$first->modify('+1 month')->format('Y-m-d')]) as $booking) {$booking['description']='Scheduled application';$booking['application']=true;$byDay[(int)date('j',strtotime($booking['event_date']))][]=$booking;}
$page_id='events';$page_title='Parish Event Calendar';require __DIR__.'/includes/layout.php';
?><div class="card"><div class="card-body"><h2>Parish event calendar</h2><form method="get"><select name="parish_id"><?php foreach($parishes as $p):?><option value="<?=$p['id']?>" <?=$pid===$p['id']?'selected':''?>><?=htmlspecialchars($p['name'])?></option><?php endforeach;?></select><input type="month" name="month" value="<?=htmlspecialchars($month)?>"><button class="btn-sm btn-navy">View calendar</button></form><div style="overflow:auto"><table style="table-layout:fixed;min-width:650px"><thead><tr><?php foreach(['Mon','Tue','Wed','Thu','Fri','Sat','Sun'] as $day):?><th><?=$day?></th><?php endforeach;?></tr></thead><tbody><tr><?php for($cell=0;$cell<(int)ceil(($days+$offset)/7)*7;$cell++):$day=$cell-$offset+1;if($cell&&$cell%7===0)echo '</tr><tr>';?><td style="vertical-align:top;height:110px"><?php if($day>0&&$day<=$days):?><strong><?=$day?></strong><?php foreach($byDay[$day]??[] as $event):?><p><?php if(!empty($event['application'])): ?><a href="application.php?id=<?= (int)$event['id'] ?>" class="pill pill-navy">Scheduled application</a><?php else: ?><span class="pill pill-gold">Event</span><?php endif; ?><br><b><?=htmlspecialchars(date('g:i A',strtotime($event['event_date'])))?></b> <?=htmlspecialchars($event['title'])?><br><small><?=htmlspecialchars($event['description']??'')?></small></p><?php endforeach;endif;?></td><?php endfor;?></tr></tbody></table></div></div></div><?php require __DIR__.'/includes/layout_footer.php';?>
