<?php
require_once __DIR__.'/../includes/access.php';
if(($_GET['view']??'')==='available'){require __DIR__.'/../includes/calendar_availability.php';exit;}
$pid=(int)($_GET['parish_id']??$user['parish_id']??0);$month=$_GET['month']??date('Y-m');
if(!preg_match('/^[0-9]{4}-(0[1-9]|1[0-2])$/',$month))$month=date('Y-m');
$first=new DateTimeImmutable($month.'-01');$days=(int)$first->format('t');$offset=(int)$first->format('N')-1;
$parishes=$conn->query("SELECT id,name FROM parishes WHERE status='active'")->fetch_all(MYSQLI_ASSOC);if(!$pid&&$parishes)$pid=(int)$parishes[0]['id'];
$events=$conn->execute_query("SELECT * FROM events WHERE parish_id=? AND status='active' AND event_date>=? AND event_date<? ORDER BY event_date",[$pid,$first->format('Y-m-d'),$first->modify('+1 month')->format('Y-m-d')])->fetch_all(MYSQLI_ASSOC);$byDay=[];foreach($events as $event)$byDay[(int)date('j',strtotime($event['event_date']))][]=$event;
foreach($conn->execute_query("SELECT a.id,a.user_id,a.schedule event_date,s.name title FROM applications a JOIN services s ON s.id=a.service_id WHERE a.parish_id=? AND a.status IN ('pending','approved') AND a.schedule>=? AND a.schedule<? ORDER BY a.schedule",[$pid,$first->format('Y-m-d'),$first->modify('+1 month')->format('Y-m-d')]) as $booking) {$booking['description']='Scheduled application';$booking['application']=(int)$booking['user_id']===(int)$user['id'];$byDay[(int)date('j',strtotime($booking['event_date']))][]=$booking;}
// Recurring Mass times belong to the selected parish and month.
foreach($conn->execute_query("SELECT day_of_week,time_start,mass_type AS title FROM mass_schedules WHERE parish_id=? AND status='active'",[$pid]) as $mass){for($n=1;$n<=$days;$n++){$date=$first->setDate((int)$first->format('Y'),(int)$first->format('m'),$n);if($date->format('l')===$mass['day_of_week'])$byDay[$n][]=['event_date'=>$date->format('Y-m-d').' '.$mass['time_start'],'title'=>$mass['title']?:'Mass','description'=>'Recurring Mass'];}}
$page_id='events';$page_title='Parish Event Calendar';require __DIR__.'/includes/layout.php';
?>
<nav class="request-tabs"><a href="?view=available&amp;parish_id=<?= $pid ?>&amp;month=<?= h($month) ?>">Available Dates</a><a aria-current="page" href="?parish_id=<?= $pid ?>&amp;month=<?= h($month) ?>">Scheduled Dates</a></nav><div class="sec-head"><div><div class="sec-tag">Parish schedules</div><h1 class="sec-title">Parish Event Calendar</h1></div></div>
<div class="card"><div class="card-body"><form method="get" class="filter-bar"><label>Parish<select name="parish_id"><?php foreach($parishes as $p):?><option value="<?= (int)$p['id'] ?>" <?= $pid===(int)$p['id']?'selected':'' ?>><?= h($p['name']) ?></option><?php endforeach;?></select></label><label>Month<input type="month" name="month" value="<?= h($month) ?>"></label><button class="btn-sm btn-navy">View calendar</button></form>
<div class="tbl-wrap"><table style="table-layout:fixed;min-width:560px"><thead><tr><?php foreach(['Mon','Tue','Wed','Thu','Fri','Sat','Sun'] as $day):?><th><?= $day ?></th><?php endforeach;?></tr></thead><tbody><tr>
<?php for($cell=0;$cell<(int)ceil(($days+$offset)/7)*7;$cell++):$day=$cell-$offset+1;if($cell&&$cell%7===0)echo '</tr><tr>';?><td style="vertical-align:top;height:90px"><?php if($day>0&&$day<=$days):?><strong><?= $day ?></strong><?php if(!empty($byDay[$day])): ?><button type="button" class="btn-sm btn-outline" style="display:block;white-space:normal" onclick="document.getElementById('day-<?= $day ?>').showModal()" aria-label="View schedules for <?= h($month.'-'.$day) ?>"><?php foreach(array_slice($byDay[$day],0,2) as $event): ?><?= h(date('g:i A',strtotime($event['event_date'])).' — '.$event['title']) ?><br><?php endforeach;?><?= count($byDay[$day]) ?> scheduled</button><?php endif;endif;?></td><?php endfor;?></tr></tbody></table></div></div></div>
<?php foreach($byDay as $day=>$items): ?><dialog id="day-<?= (int)$day ?>" style="margin:auto;padding:24px;border:0;border-radius:12px;max-width:min(540px,92vw);max-height:85vh;overflow:auto"><h2><?= h($month.'-'.$day) ?></h2><?php foreach($items as $event): ?><article class="announcement-article"><h3><?= h(date('g:i A',strtotime($event['event_date'])).' — '.$event['title']) ?></h3><p><?= h($event['description']??'') ?></p><?php if(!empty($event['application'])): ?><a href="application.php?id=<?= (int)$event['id'] ?>">Scheduled application details</a><?php endif;?></article><?php endforeach;?><form method="dialog"><button class="btn-sm btn-outline">Close</button></form></dialog><?php endforeach;?>
<?php require __DIR__.'/includes/layout_footer.php'; ?>
