<?php
require_once __DIR__.'/../includes/access.php';require_once __DIR__.'/../includes/help.php';
$parishes=$conn->query("SELECT id,name FROM parishes WHERE status='active' ORDER BY name")->fetch_all(MYSQLI_ASSOC);
$pid=(int)($_POST['parish_id']??$_GET['parish_id']??$user['parish_id']??0);if(!$pid&&$parishes)$pid=(int)$parishes[0]['id'];$notice='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{$conn->begin_transaction();help_question($user,$pid,trim($_POST['question']??''));$conn->commit();header('Location: help.php?parish_id='.$pid);exit;}
 catch(Throwable $e){$conn->rollback();$notice=$e instanceof DomainException?$e->getMessage():'Unable to send your inquiry.';}
}
$thread=sqlrow('SELECT * FROM help_conversations WHERE user_id=? AND parish_id=?',[$user['id'],$pid]);
$messages=$thread?$conn->execute_query('SELECT m.*,u.name sender_name FROM messages m JOIN users u ON u.id=m.sender_id WHERE m.parish_id=? AND ((m.sender_id=? AND m.receiver_id=?) OR (m.sender_id=? AND m.receiver_id=?)) ORDER BY m.id',[$pid,$user['id'],$thread['secretary_id'],$thread['secretary_id'],$user['id']])->fetch_all(MYSQLI_ASSOC):[];
if(($_GET['ajax']??'')==='thread'){header('Content-Type: application/json');echo json_encode(['messages'=>$messages,'staff_active'=>(bool)($thread['staff_active']??false)]);exit;}
$page_title='Parish Help and Messages';$page_id='help';require __DIR__.'/includes/layout.php';
?><div class="card"><div class="card-body"><h2>Parish help and messages</h2><p>Answers come from this parish's published FAQs. When there is no reliable match, the parish secretary receives your inquiry and replies here.</p><p><?=htmlspecialchars($notice)?></p><form method="get"><label>Parish <select name="parish_id" onchange="this.form.submit()"><?php foreach($parishes as $parish):?><option value="<?=$parish['id']?>" <?=$pid===$parish['id']?'selected':''?>><?=htmlspecialchars($parish['name'])?></option><?php endforeach;?></select></label></form><p id="helpState"><?=!empty($thread['staff_active'])?'The secretary is handling this conversation.':'FAQ assistant ready.'?></p><div id="helpMessages" aria-live="polite" style="max-height:440px;overflow:auto"><?php foreach($messages as $m):?><article style="padding:14px;margin:10px 0;background:#F8F6F2;border-radius:10px"><strong><?=$m['is_bot']?'FAQ assistant':((int)$m['sender_id']===(int)$user['id']?'You':'Parish staff — '.htmlspecialchars($m['sender_name']))?></strong><p><?=nl2br(htmlspecialchars($m['body']))?></p></article><?php endforeach;?></div><form method="post"><input type="hidden" name="parish_id" value="<?=$pid?>"><div class="form-group"><label>Your question or reply</label><textarea name="question" required minlength="2" maxlength="2000"></textarea></div><button class="btn-sm btn-navy">Send</button></form><p><a href="messages.php">View existing message history</a> · <a href="faq.php?parish_id=<?=$pid?>">Browse parish FAQs</a></p></div></div>
<script>let lastHelp=<?=json_encode(json_encode($messages))?>;setInterval(async()=>{if(document.hidden)return;try{const d=await fetch('help.php?ajax=thread&parish_id=<?=$pid?>').then(r=>r.json());const key=JSON.stringify(d.messages);if(key===lastHelp)return;lastHelp=key;const box=document.getElementById('helpMessages');box.replaceChildren();d.messages.forEach(m=>{const article=document.createElement('article');article.style='padding:14px;margin:10px 0;background:#F8F6F2;border-radius:10px';const label=document.createElement('strong');label.textContent=Number(m.is_bot)?'FAQ assistant':(Number(m.sender_id)===<?=$user['id']?>?'You':'Parish staff — '+m.sender_name);const body=document.createElement('p');body.style.whiteSpace='pre-wrap';body.textContent=m.body;article.append(label,body);box.append(article);});document.getElementById('helpState').textContent=d.staff_active?'The secretary is handling this conversation.':'FAQ assistant ready.';}catch(e){}},5000);</script>
<?php require __DIR__.'/includes/layout_footer.php';?>
